# Generated by Django 6.0.3 on 2026-03-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
