# Generated by Django 6.0.3 on 2026-03-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('reader', '0002_reader_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='books',
            field=models.ManyToManyField(related_name='readers', to='book.book'),
        ),
    ]
