# Generated by Django 6.0.3 on 2026-03-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_reader_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='password',
            field=models.CharField(default='password123', max_length=128),
        ),
    ]
